# local_story.gd
extends Node

const LOCAL_SCRIPT = [
	# ================= 序章：图书馆里的相遇 =================
	{"type": "change_background", "background": "duxia"},
	{"type": "play_audio", "audio_id": "gentle"},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "sad"}},
	{"type": "show_dialogue", "character": "xiu", "text": "（轻声）你还好吗？我看你在这里坐了好久，书都没翻几页……"},
	{"type": "show_dialogue", "character": "", "text": "你抬起头，发现小貅正关切地看着你。"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "是不是最近压力太大了？[shake rate=10 level=3]别一个人扛着呀！[/shake]"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "唉，确实有点累。"}, {"id": 2, "text": "没什么，我能应付。"}]},
	{"type": "add_affection", "character": "xiu", "delta": 5},
	{"type": "show_dialogue", "character": "xiu", "text": "我懂那种感觉。不过今天天气这么好，我们出去走走吧！"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	{"type": "set_expression", "character": "xiu", "expression": "happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "[color=#FFB6C1]校园里的春梅开了，好漂亮的，我带你去看！[/color]"},
	
	# 仙林校区：香雪海
	{"type": "change_background", "background": "xiangxuehai"},
	{"type": "show_dialogue", "character": "xiu", "text": "当当~香雪海到啦！这是仙林校区最美的地方之一，春天梅花盛开的时候，整片山坡都是粉色的。"},
	{"type": "show_dialogue", "character": "xiu", "text": "虽然现在梅花还没开，但这片草地和凉亭也很惬意。我们坐一会儿吧。"},
	{"type": "long_dialogue", "text": "你们在香雪海的凉亭里坐下。微风拂面，远处传来学生的欢笑声。小貅从口袋里掏出一颗糖递给你，自己也剥开一颗。阳光透过树叶洒在石桌上，斑驳的光影轻轻晃动。"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "（嚼着糖）你知道吗？我压力大的时候，就喜欢来这里坐着。看看天，看看草，什么都不想。等回过神来，烦恼好像就轻了。"},
	{"type": "show_dialogue", "character": "xiu", "text": "[color=#FFD700]南大的校训是“诚朴雄伟，励学敦行”，但其实，我们也要学会“励心”呀。[/color]"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "你说得对，我需要放松一下。"}, {"id": 2, "text": "可是还有很多事没做完……"}]},
	{"type": "add_affection", "character": "xiu", "delta": 5},
	{"type": "set_expression", "character": "xiu", "expression": "happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "事情是做不完的，但快乐是可以攒的！今天我们就攒一点快乐能量吧。"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	
	# 前往鼓楼校区
	{"type": "show_dialogue", "character": "xiu", "text": "对了，想不想去鼓楼校区逛逛？那可是南大的老校区，有百年的北大楼和礼堂，超级有韵味！"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "好啊，反正今天不想学习了。"}, {"id": 2, "text": "有点远吧？"}]},
	{"type": "show_dialogue", "character": "xiu", "text": "不远不远，坐地铁二号线一会儿就到！走，我带你体验一把“跨校区一日游”！"},
	
	{"type": "change_background", "background": "gate"},
	{"type": "play_audio", "audio_id": "smooth","crossfade": 1},
	{"type": "show_dialogue", "character": "xiu", "text": "看，这就是鼓楼校区的正门！是不是特别气派？上面“南京大学”四个字，是毛主席的亲笔题字呢。"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "鼓楼校区是南大的根，很多民国时期的建筑都保存完好。你闻到空气中那股淡淡的梧桐香了吗？这是属于老校区的独特味道。"},
	
	# 北大楼（简介，详细在后续）
	{"type": "change_background", "background": "beidalou"},
	{"type": "show_dialogue", "character": "xiu", "text": "到了到了！这就是传说中的北大楼！建于1919年，满墙的爬山虎是它的勋章。"},
	{"type": "set_expression", "character": "xiu", "expression": "surprised"},
	{"type": "show_dialogue", "character": "xiu", "text": "哇~你看爬山虎的叶子，春天嫩绿，夏天浓荫，秋天火红，冬天静默。就像人的情绪，有起有落，都是自然的。"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "这里真美，让人心静。"}, {"id": 2, "text": "谢谢你，我好像想通了一点。"}]},
	{"type": "add_affection", "character": "xiu", "delta": 10},
	
	# 小径偶遇宋青
	{"type": "set_expression", "character": "xiu", "expression": "happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "走吧，我带你去一条很少人知道的小径。那里的紫藤花架特别安静。"},
	{"type": "change_background", "background": "path"},
	{"type": "play_audio", "audio_id": "flowing","crossfade": 1},
	{"type": "show_dialogue", "character": "", "text": "就在这时，前方走来一个修长的身影。他穿着白衬衫，气质清冷，但眼神温和。"},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}, "right": {"id": "song", "expression": "slight_smile"}},
	{"type": "show_dialogue", "character": "song", "text": "小貅？还有……新同学？"},
	{"type": "show_dialogue", "character": "xiu", "text": "啊，宋青学长！你也来散步？"},
	{"type": "set_expression", "character": "song", "expression": "happy"},
	{"type": "show_dialogue", "character": "song", "text": "（转向你）欢迎来到南大。不管哪个阶段，都会有压力。但记住，你不是一个人在走。"},
	{"type": "set_expression", "character": "song", "expression": "default"},
	{"type": "show_dialogue", "character": "song", "text": "对了，我今天还有事，先不打扰你们了。祝玩的开心！"},
	{"type": "character_action", "character": "song", "action": "nod"},
	{"type": "add_affection", "character": "song", "delta": 5},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}},
	
	# 苏浙运动场
	{"type": "change_background", "background": "playground_gulou"},
	{"type": "play_audio", "audio_id": "active","crossfade": 1},
	{"type": "show_dialogue", "character": "xiu", "text": "最后，我们去运动场跑几圈！苏浙运动场，见证了多少南大人的汗水与青春！"},
	{"type": "show_dialogue", "character": "", "text": "你们在跑道上慢跑起来。夕阳西下，运动场上洒满金色的余晖。"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	{"type": "show_dialogue", "character": "xiu", "text": "怎么样？是不是全身舒坦？以后我们经常来运动，我陪你！"},
	{"type": "show_dialogue", "character": "xiu", "text": "今天逛了好多地方呀——香雪海、北大楼、小径、运动场……我们的南大是不是很厉害？"},
	{"type": "set_expression", "character": "xiu", "expression": "very_happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "[wave amp=50.0 freq=5.0]记住哦，不开心的时候，就来找我！我是你的专属充电宝——小貅！[/wave]"},
	{"type": "add_affection", "character": "xiu", "delta": 15},
	{"type": "show_dialogue", "character": "xiu", "text": "好啦，我们回去吧。今晚早点睡，明天又是新的一天！"},
	
	# ================= 第一幕：教室与花海的清晨 =================
	{"type": "change_background", "background": "gate"},
	{"type": "play_audio", "audio_id": "spring_forest","crossfade": 1},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "happy"}},
	{"type": "show_dialogue", "character": "xiu", "text": "早上好！昨晚睡得好吗？今天阳光超级好，我们去教室和花海看看。"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	
	{"type": "change_background", "background": "classroom"},
	{"type": "show_dialogue", "character": "xiu", "text": "这是我们的教学楼。你看，阳光透过窗户洒在课桌上，是不是很有学习的感觉？"},
	{"type": "show_dialogue", "character": "xiu", "text": "我特别喜欢坐靠窗的位置。累了就看看窗外的梧桐树，听听鸟叫，心情立刻就好了。"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "好啊，我们坐一会儿。"}, {"id": 2, "text": "还是去外面走走吧。"}]},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "嗯嗯，其实大学里最重要的不是学了什么，而是学会了如何学习。"},
	{"type": "add_affection", "character": "xiu", "delta": 5},
	
	{"type": "change_background", "background": "flowers"},
	{"type": "particle_play", "effect_id": "petal"},
	{"type": "set_expression", "character": "xiu", "expression": "surprised"},
	{"type": "show_dialogue", "character": "xiu", "text": "看！这里是一片花海！春天的时候，这里会开满各种颜色的花，超级浪漫！"},
	{"type": "set_expression", "character": "xiu", "expression": "very_happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "[wave amp=50.0 freq=5.0]来，闭上眼睛，深呼吸——闻到花香了吗？[/wave]"},
	{"type": "long_dialogue", "text": "你们站在花丛中，微风轻拂，花瓣轻轻摇曳。小貅轻轻哼起一首歌谣。"},
	{"type": "show_dialogue", "character": "xiu", "text": "你听说过“园艺疗法”吗？大自然是最好的心理医生。"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "这里太美了，我想常来。"}, {"id": 2, "text": "小貅，你懂得真多。"}]},
	{"type": "add_affection", "character": "xiu", "delta": 5},
	{"type": "particle_stop", "effect_id": "petal"},
	
	# ================= 第二幕：大礼堂的音乐疗愈 =================
	{"type": "change_background", "background": "gate"},
	{"type": "play_audio", "audio_id": "gentle","crossfade": 1},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "happy"}},
	{"type": "show_dialogue", "character": "xiu", "text": "早上好！今天有一个超级大惊喜——我弄到了大礼堂音乐会的票！"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	{"type": "show_dialogue", "character": "xiu", "text": "校乐团今天要排练德彪西的《月光》，走吧走吧！"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "你真是太厉害了！"}, {"id": 2, "text": "我对古典音乐不太了解……"}]},
	{"type": "show_dialogue", "character": "xiu", "text": "没关系！音乐不需要了解，只需要感受。"},
	
	{"type": "change_background", "background": "litang"},
	{"type": "show_dialogue", "character": "xiu", "text": "你看，这就是大礼堂。1930年建成，杨廷宝先生设计，中西合璧的风格。"},
	{"type": "set_expression", "character": "xiu", "expression": "surprised"},
	{"type": "show_dialogue", "character": "xiu", "text": "不管看几次，大礼堂带给我的震撼是一点不少呢！"},
	{"type": "show_dialogue", "character": "", "text": "你们悄悄推开厚重的木门，空旷的观众席只有寥寥几人。舞台上，钢琴手正在演奏，音符如月光般倾泻而下。"},
	{"type": "play_audio", "audio_id": "love_piano","crossfade": 1},
	{"type": "long_dialogue", "text": "你们找了个中间的位置坐下。钢琴的音符如水般流淌，在穹顶下回荡。你闭上眼睛，仿佛置身于一片宁静的湖泊。"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "（耳语）心理学上有个词叫“心流”。当我们完全沉浸在音乐中时，大脑会释放出多巴胺。"},
	{"type": "show_dialogue", "character": "xiu", "text": "德彪西的《月光》其实不是描写月亮的，而是描写那种被月光笼罩的宁静。"},
	{"type": "character_action", "character": "xiu", "action": "shake"},
	{"type": "set_expression", "character": "xiu", "expression": "happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "[wave amp=50.0 freq=5.0]所以，不开心的时候就来找我吧，我带你听音乐！[/wave]"},
	{"type": "add_affection", "character": "xiu", "delta": 5},
	
	# 偶遇宋青
	{"type": "change_background", "background": "gate"},
	{"type": "show_dialogue", "character": "xiu", "text": "咦，那不是宋青学长吗？"},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}, "right": {"id": "song", "expression": "slight_smile"}},
	{"type": "show_dialogue", "character": "song", "text": "你们刚从大礼堂出来？"},
	{"type": "show_dialogue", "character": "xiu", "text": "对呀！刚听完《月光》，超级治愈！"},
	{"type": "show_dialogue", "character": "song", "text": "音乐确实是良药。如果感兴趣，可以来行政楼三楼心理中心找我。"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "我想去看看。"}, {"id": 2, "text": "下次有机会吧。"}]},
	{"type": "show_dialogue", "character": "xiu", "text": "那我们一起去行政楼吧，就当认个路！"},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}},
	
	# ================= 第三幕：心理中心的心灵加油站 =================
	{"type": "change_background", "background": "nansu"},
	{"type": "play_audio", "audio_id": "flowing","crossfade": 1},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "happy"}},
	{"type": "show_dialogue", "character": "xiu", "text": "看，这就是我们学校的心理中心！暖色调的灯光，柔软的沙发，就像家里的客厅。"},
	{"type": "show_dialogue", "character": "xiu", "text": "你看到墙上那些画了吗？那都是来体验的同学画的“情绪曼陀罗”。"},
	{"type": "long_dialogue", "text": "你环顾四周。墙上贴满了五彩斑斓的曼陀罗图案，角落里摆着沙盘，阳光透过百叶窗洒在地毯上，空气里飘着淡淡的薰衣草香。"},
	
	{"type": "show_dialogue", "character": "xiu", "text": "那边是放松椅，这边是沙盘游戏区，里面还有情绪宣泄室！"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "我想试试那个放松椅。"}, {"id": 2, "text": "沙盘游戏看起来很有趣。"}]},
	{"type": "show_dialogue", "character": "xiu", "text": "哈哈，今天我们先做正念冥想！"},
	
	{"type": "show_dialogue", "character": "", "text": "这时，宋青学长端着一杯热茶走了出来。"},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}, "right": {"id": "song", "expression": "slight_smile"}},
	{"type": "show_dialogue", "character": "song", "text": "（将茶递给你）先喝杯热茶，这是薰衣草洋甘菊茶，有镇静的效果。"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "谢谢学长。"}, {"id": 2, "text": "学长考虑得真周到。"}]},
	{"type": "set_expression", "character": "song", "expression": "very_happy"},
	{"type": "show_dialogue", "character": "song", "text": "真是个会说话的好孩子~"},
	{"type": "set_expression", "character": "song", "expression": "default"},
	{"type": "show_dialogue", "character": "song", "text": "对了，我还有工作要忙，先走咯"},
	{"type": "add_affection", "character": "song", "delta": 5},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}},
	
	{"type": "show_dialogue", "character": "xiu", "text": "好啦，我们进冥想室吧。"},
	{"type": "long_dialogue", "text": "你坐在舒适的沙发上，耳边是轻柔的引导语。你从未如此认真地感受过自己的呼吸。十五分钟后，你睁开眼睛，窗外的阳光格外明亮。"},
	{"type": "add_affection", "character": "xiu", "delta": 10},
	{"type": "set_expression", "character": "xiu", "expression": "very_happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "感觉怎么样？是不是整个人都轻盈了？"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "真的很有效！"}, {"id": 2, "text": "谢谢你带我来这里。"}]},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "[color=#87CEEB]记住哦——关心自己的心灵，不是软弱，而是智慧。[/color]"},
	
	# 感恩墙
	{"type": "show_dialogue", "character": "", "text": "你们走出冥想室，小貅拉着你停在一面墙前。"},
	{"type": "show_dialogue", "character": "xiu", "text": "看，这是“感恩墙”。要不要也写一张？"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "好，我写一张。"}, {"id": 2, "text": "我想想……"}]},
	{"type": "show_dialogue", "character": "", "text": "你拿起笔，在便签上写下了一行字。小貅凑过来看，眼睛亮亮的。"},
	{"type": "set_expression", "character": "xiu", "expression": "surprised"},
	{"type": "show_dialogue", "character": "xiu", "text": "哇，写得真好！"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	{"type": "add_affection", "character": "xiu", "delta": 5},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "时候不早了，我们赶紧去跑个步，正好当作放松一下吧！"},
	
	# ================= 第四幕：操场的夜跑与星空 =================
	{"type": "change_background", "background": "playground_gulou"},
	{"type": "play_audio", "audio_id": "active","crossfade": 1},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "happy"}},
	{"type": "show_dialogue", "character": "xiu", "text": "晚上的操场特别有气氛！运动时大脑会分泌内啡肽，天然的快乐激素哦。"},
	{"type": "show_dialogue", "character": "xiu", "text": "来，先跟我做几个拉伸动作。"},
	{"type": "long_dialogue", "text": "你们沿着跑道慢跑起来。起初脚步有些沉重，但跑过一圈后，身体渐渐找到了节奏。晚风拂过脸颊，汗水从额头滑落。"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "哈……哈……两圈了！感觉怎么样？"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "真的，跑完感觉整个人都轻松了。"}, {"id": 2, "text": "原来运动这么舒服！"}]},
	{"type": "add_affection", "character": "xiu", "delta": 5},
	
	{"type": "show_dialogue", "character": "", "text": "你们在看台上休息，夕阳已经完全落下，天空从橙红色渐变成深蓝。"},
	{"type": "set_expression", "character": "xiu", "expression": "confused"},
	{"type": "show_dialogue", "character": "xiu", "text": "咦，你看那边……那个穿着白衬衫的人是不是宋青学长？"},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}, "right": {"id": "song", "expression": "slight_smile"}},
	{"type": "show_dialogue", "character": "song", "text": "你们果然在这里。之前那本书看完了吗？"},
	{"type": "show_dialogue", "character": "song", "text": "书里说，真正的幸福不在于没有痛苦，而在于你如何与痛苦共处。"},
	{"type": "character_action", "character": "song", "action": "nod"},
	{"type": "add_affection", "character": "song", "delta": 5},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}},
	{"type": "show_dialogue", "character": "xiu", "text": "学长再见！好，我们也差不多该去最后一个地方了——图书馆穹顶。"},
	
	{"type": "change_background", "background": "duxia_night"},
	{"type": "play_audio", "audio_id": "gentle","crossfade": 1},
	{"type": "show_dialogue", "character": "xiu", "text": "这里是杜厦图书馆的穹顶下面。你看，透明的穹顶可以看到整片天空。"},
	{"type": "show_dialogue", "character": "xiu", "text": "（望着穹顶）你看，那颗最亮的星是木星。它周围其实有很多小卫星在环绕着它。"},
	{"type": "show_dialogue", "character": "xiu", "text": "我们每个人也都像一颗小卫星，在自己的轨道上运行。有时孤独，有时迷茫，但其实我们从来都不孤单。"},
	{"type": "set_expression", "character": "xiu", "expression": "very_happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "[wave amp=50.0 freq=5.0]记住哦！你不是一颗孤独的星。我会一直守护着你！[/wave]"},
	{"type": "add_affection", "character": "xiu", "delta": 10},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "（轻声）好啦，天已经很晚啦。明天早上，太阳还会照常升起。"},
	
	# ================= 第五幕：梧桐树下，诚朴雄伟 =================
	{"type": "change_background", "background": "gate"},
	{"type": "play_audio", "audio_id": "smooth","crossfade": 1},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}},
	{"type": "show_dialogue", "character": "xiu", "text": "（安静地）你来了。今天宋青学长也在，我们说好一起送你一份礼物。"},
	{"type": "set_characters", "left": {"id": "xiu", "expression": "default"}, "right": {"id": "song", "expression": "slight_smile"}},
	{"type": "show_dialogue", "character": "song", "text": "这几天看到你状态好了很多。笑容也比以前多了。"},
	{"type": "set_expression", "character": "xiu", "expression": "happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "对吧对吧！我就说嘛，我们南大的治愈魔法是很灵的！"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "set_expression", "character": "song", "expression": "happy"},
	{"type": "show_dialogue", "character": "song", "text": "今天带你来这里，是想让你重新认识一下这座校门。你第一天来南大的时候，就是从这里走进来的。"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "其实很紧张，也很迷茫。"}, {"id": 2, "text": "记不太清了，好像很匆忙。"}]},
	{"type": "show_dialogue", "character": "song", "text": "但你看，几天过去了。你走过了北大楼、大礼堂、图书馆、运动场。你已经不是几天前那个愁眉苦脸的人了。"},
	{"type": "show_dialogue", "character": "xiu", "text": "说到礼物——我们给你准备了一样东西！"},
	{"type": "show_dialogue", "character": "", "text": "你打开信封，里面是一张手工制作的卡片。封面上画着一棵梧桐树，树下站着一个笑着的小人。"},
	{"type": "long_dialogue", "text": "“亲爱的朋友：欢迎来到南大。这里不是完美的地方，但这里有愿意陪你走过低谷的人。当你觉得孤独的时候，就去北大楼看看爬山虎——它们用了百年时间，才爬满了整面墙。所以，慢慢来，你不需要一下子就长大。我们在这里，一直在。”"},
	{"type": "add_affection", "character": "xiu", "delta": 15},
	
	{"type": "change_background", "background": "beidalou"},
	{"type": "show_dialogue", "character": "xiu", "text": "最后，我们再来看看北大楼吧。你看爬山虎，它们不是一天就爬满整面墙的。"},
	{"type": "show_dialogue", "character": "xiu", "text": "我们也一样。不需要一下子就变得完美。每天进步一点点，就像爬山虎一样，总有一天会铺满自己的天空。"},
	{"type": "set_expression", "character": "song", "expression": "default"},
	{"type": "show_dialogue", "character": "song", "text": "南大的校训是“诚朴雄伟，励学敦行”。前四个字是目标，后四个字是方法。"},
	{"type": "show_dialogue", "character": "song", "text": "但我想再加四个字——“温柔待己”。无论什么时候，记得对自己好一点。"},
	{"type": "set_expression", "character": "xiu", "expression": "happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "[wave amp=50.0 freq=5.0]对对对！温柔待己！这是我听过最美的校训！[/wave]"},
	{"type": "add_affection", "character": "xiu", "delta": 10},
	
	{"type": "change_background", "background": "flowers"},
	{"type": "particle_play", "effect_id": "petal"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "show_dialogue", "character": "xiu", "text": "好啦，太阳快落山了。我们今天的故事就到这里，但不是结束。"},
	{"type": "show_dialogue", "character": "xiu", "text": "（转过身，认真地看着你）现在是你的主场了。你有没有什么话想对我们说？"},
	{"type": "show_choices", "choices": [{"id": 1, "text": "谢谢你，小貅。谢谢学长。我好像不再害怕了。"}, {"id": 2, "text": "我想抱抱几天前的自己，告诉ta一切都会好的。"}]},
	{"type": "set_expression", "character": "xiu", "expression": "sad"},
	{"type": "show_dialogue", "character": "xiu", "text": "（眼眶有些湿润）[shake rate=15 level=3]呜……你说得我都想哭了！[/shake]"},
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "set_expression", "character": "song", "expression": "very_happy"},
	{"type": "show_dialogue", "character": "song", "text": "（轻轻拍了一下你的肩）你已经找到了属于自己的力量。"},
	{"type": "character_action", "character": "song", "action": "nod"},
	
	{"type": "show_dialogue", "character": "song", "text": "最后送你一首小诗吧："},
	{"type": "long_dialogue", "text": "“你要记得那些黑暗中默默抱紧你的人，\n逗你笑的人，陪你彻夜聊天的人，\n坐车来看望你的人，说想念你的人。\n是这些人组成你生命中一点一滴的温暖，\n是这些温暖使你远离阴霾，\n是这些温暖使你成为善良的人。”"},
	{"type": "set_expression", "character": "xiu", "expression": "very_happy"},
	{"type": "show_dialogue", "character": "xiu", "text": "[wave amp=50.0 freq=5.0]所以！让我们一起做温暖的人吧！[/wave]"},
	{"type": "character_action", "character": "xiu", "action": "bounce"},
	{"type": "add_affection", "character": "xiu", "delta": 20},
	{"type": "add_affection", "character": "song", "delta": 20},
	
	{"type": "set_expression", "character": "xiu", "expression": "default"},
	{"type": "set_expression", "character": "song", "expression": "default"},
	{"type": "show_dialogue", "character": "", "text": "夕阳终于落下。你们三个并排站在花海前，影子被拉得很长很长。"},
	{"type": "show_dialogue", "character": "", "text": "远处传来钟楼的整点报时。浑厚的钟声在校园里回荡，一声又一声。"},
	{"type": "set_variable", "variable": "ending_type", "value": 1},
	{"type": "set_variable", "variable": "story_complete", "value": true},
	{"type": "show_dialogue", "character": "", "text": "[color=#FFD700]诚朴雄伟，励学敦行。温柔待己，温暖待人。[/color]"},
	{"type": "show_dialogue", "character": "", "text": "[color=#FFD700]这是南大教给你的第一课，也是最重要的一课。[/color]"},
	{"type": "show_dialogue", "character": "", "text": "你的故事才刚刚开始。愿此间的温暖，伴你走过万水千山。"},
	{"type": "stop_audio", "audio_id": "smooth"},
	{"type": "play_audio", "audio_id": "gentle"},
	{"type": "set_ui_state", "element": "DialogueBox", "state": "hidden"},
	{"type": "end_scene"}
]

func execute_local_story() -> void:
	if not has_node("/root/ScriptEngine"):
		return
	print("[LocalStory] 正在播放本地剧情...")
	ScriptEngine.execute_commands(LOCAL_SCRIPT.duplicate(true))
